server:
  port: 8081

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: book-service
          uri: ${BOOK_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/books/**
          filters:
            - AddRequestHeader=X-Tenant,lerma-corps
            - AddResponseHeader=X-Gender,fantasy
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cas.lerma-corps.com/realms/zepe-realm
          jwk-set-uri: https://cas.lerma-corps.com/realms/zepe-realm/protocol/openid-connect/certs

token:
  converter:
    principal-attribute: preferred_username
    resource-id: ${OIDC_CLIENT_ID:admin-cli}
